name: CI

on: [push]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Tests with Coverage
        run: mvn clean verify

      # 📌 Affichage des résultats des tests directement dans GitHub
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit

      # 📌 Upload du rapport de couverture en tant qu'artefact téléchargeable
      - name: Upload Coverage Report (XML + HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/site/jacoco

      # 📌 Génération d'un badge de couverture pour le README
      - name: Generate Coverage Badge
        if: always()
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges

      # 📌 Upload du badge pour qu'il soit accessible dans le README
      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/badges

      # 📌 Génération d'un commentaire avec la couverture dans la PR
      - name: Report Coverage in PR 📌
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: target/site/jacoco/jacoco.xml
